#!/bin/python3

import numpy as np

if __name__ == '__main__':
    # Nhập số nguyên n
    n = int(input().strip())
    
    # Tạo numpy array từ 0 đến n-1
    arr = np.arange(n)
    
    # Thay thế các giá trị lẻ bằng -1
    arr[arr % 2 != 0] = -1
    
    # In ra màn hình numpy array
    print(arr)

